name: Build Packages and Create Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write   # create release + upload assets
  packages: read    # pull image from GHCR

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository }}:main
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mark repo as safe for git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Cache libhdf5-static-pic
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.GITHUB_WORKSPACE }}/pkg/libhdf5-static-pic_2.0.0_amd64.deb
          key: >
            cmake-build-${{ runner.os }}-${{ env.BUILD_TYPE }}-
            ${{ hashFiles('pkg/libhdf5-static-pic/debian/rules') }}
          #restore-keys: |
          #  cmake-build-${{ runner.os }}-${{ env.BUILD_TYPE }}-

      - name: Build packages
        run: |
          chmod +x ./build-packages.sh
          ./build-packages.sh

      - name: List built packages (debug)
        run: ls -lah pkg

      - name: Create GitHub Release and upload .deb files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            pkg/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

